language: ruby
branches:
  only:
    - rails3
env:
  - DB=mysql
  - DB=postgres
  - DB=sqlite
services:
  - mysql
  - postgresql
rvm:
  - "1.8.7"
  - "1.9.3"
before_script:
  - cp config/database.yml.travis config/database.yml
  - 'echo "test: *${DB}" >> config/database.yml'
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
  - bundle exec rake db:migrate
script:
  - bundle exec rake spec
